version: '3.7'

services:
   backend:
     image: cyrilcsr/ccc_backend:1.3
     container_name: backend
     volumes:
       - /home/ubuntu/config:/home/config
     ports:
       - "5000:5000"
     restart: always
