# Common vars
availability_zone: melbourne-qh2-uom

# Volume
volumes:
  - vol_name: database-vol-1
    vol_size: 30
  - vol_name: database-vol-2
    vol_size: 30
  - vol_name: webserver_vol
    vol_size: 30
  - vol_name: backend_vol
    vol_size: 100
  # - vol_name: database-vol-2-1
  #   vol_size: 30
  # - vol_name: database-vol-2-2
  #   vol_size: 30

# Security group
security_groups:
  - name: ssh
    description: "Security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: http
    description: "Security group for HTTP"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0
  - name: https
    description: "Security group for HTTPS"
    protocol: tcp
    port_range_min: 443
    port_range_max: 443
    remote_ip_prefix: 0.0.0.0/0
  - name: CouchDB_main
    description: "Open 5984 port for access data in DB"
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_ip_prefix: 0.0.0.0/0
  - name: CouchDB_communication
    description: "Open 4369 port for DB nodes communication"
    protocol: tcp
    port_range_min: 4369
    port_range_max: 4369
    remote_ip_prefix: 0.0.0.0/0
  - name: CouchDB_nodes
    description: "Open 9100-9200 for DB nodes"
    protocol: tcp
    port_range_min: 9100
    port_range_max: 9200
    remote_ip_prefix: 0.0.0.0/0
  - name: flask
    description: "Open 5000 for flask backend"
    protocol: tcp
    port_range_min: 5000
    port_range_max: 5000
    remote_ip_prefix: 0.0.0.0/0
  - name: frontend
    description: "Open 3000 for frontend"
    protocol: tcp
    port_range_min: 3000
    port_range_max: 3000
    remote_ip_prefix: 0.0.0.0/0
# Instance
instances:
  - name: database1
    volumes: ['database-vol-1']
    instance_flavor: uom.mse.2c9g
  - name: database2
    volumes: ['database-vol-2']
    instance_flavor: uom.mse.2c9g
  - name: webserver
    volumes: ['webserver_vol']
    instance_flavor: uom.mse.1c4g
  - name: backend
    volumes: ['backend_vol']
    instance_flavor: uom.mse.2c9g

instance_image: f8b79936-6616-4a22-b55d-0d0a1d27bceb
instance_key_name: general


#test IPs
# instance_ips: ['172.26.133.42', '172.26.129.211']

# File Path
instance_ip_file: config/instance_ips.ini

# Instance login user
remote_username: ubuntu

# mount point
mounting_point: /home/ubuntu/data