# Common vars
availability_zone: melbourne-qh2-uom

# Volume
volumes:
  - vol_name: database-voltest-1
    vol_size: 30
  - vol_name: database-voltest-2
    vol_size: 30
  # - vol_name: database-vol-2-1
  #   vol_size: 30
  # - vol_name: database-vol-2-2
  #   vol_size: 30

# Security group
security_groups:
  - name: ssh
    description: "Security group for SSH access"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: http
    description: "Security group for HTTP"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0
  - name: https
    description: "Security group for HTTPS"
    protocol: tcp
    port_range_min: 443
    port_range_max: 443
    remote_ip_prefix: 0.0.0.0/0
  - name: CouchDB_main
    description: "Open 5984 port for access data in DB"
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_ip_prefix: 0.0.0.0/0
  - name: CouchDB_communication
    description: "Open 4396 port for DB nodes communication"
    protocol: tcp
    port_range_min: 4396
    port_range_max: 4396
    remote_ip_prefix: 0.0.0.0/0
  - name: CouchDB_nodes
    description: "Open 9100-9200 for DB nodes"
    protocol: tcp
    port_range_min: 9100
    port_range_max: 9200
    remote_ip_prefix: 0.0.0.0/0
# Instance
instances:
  - name: testdatabase1
    volumes: ['database-voltest-1']
  - name: testdatabase2
    volumes: ['database-voltest-2']
    #volumes: ['database-vol-2', 'demo-vol-2-2']

instance_image: f8b79936-6616-4a22-b55d-0d0a1d27bceb
instance_key_name: general
instance_flavor: uom.mse.1c4g
