version: '3.7'

services:
  frontend-node:
     image: cyrilcsr/ccc_frontend_node:1.0
     container_name: frontend_node
     volumes:
       - /home/ubuntu/config:/home/config
     ports:
       - "5000:5000"
     restart: always