---
# - name: Deploy frontend node to read IP config
#   community.docker.docker_swarm_service:
#       name: frontend_node
#       image: cyrilcsr/ccc_frontend_node:1.0
#       mounts:
#         - source: /home/ubuntu/config
#           target: /home/config
#           type: bind
#       publish:
#         - published_port: 5000
#           target_port: 5000
#           mode: host
#       restart_config:
#         condition: on-failure
#         delay: 5s
#         max_attempts: 3
#         window: 120s

# - name: Deploy frontend web app
#   community.docker.docker_swarm_service:     
#       name: frontend
#       image: cyrilcsr/ccc_frontend:1.2
#       mounts:
#         - source: /home/ubuntu/config
#           target: /home/config
#           type: bind
#       publish:
#         - published_port: 5000
#           target_port: 5000
#           mode: host
#       restart_config:
#         condition: on-failure
#         delay: 5s
#         max_attempts: 3
#         window: 120s

- name: Copy instance IP file to all instance
  become: yes
  ansible.builtin.copy:
    src: ../Docker/docker-compose/docker-frontend-app.yml
    dest: /home/ubuntu/config/instance_ips.ini


- name: Test docker swarm deploy
  ansible.builtin.shell: >
    docker stack deploy 
    --compose-file docker-compose.yml
    stackdemo

# docker stack deploy --compose-file docker-compose.yml stackdemo