---
- name: Deploy couchdb on {{ansible_default_ipv4.address}}
  community.docker.docker_compose:
    project_name: couchdb
    definition:
      version: '3.7'
      services:
        couchdb:
            container_name: couchdb
            logging:
                options:
                    max-size: 100m
            restart: always
            ports:
                - '5984:5984'
                - '5986:5986'
                - '4369:4369'
                - '9100-9200:9100-9200'
            volumes:
                - '/home/ubuntu/data:/opt/couchdb/data'
            environment:
                - COUCHDB_USER=admin
                - COUCHDB_PASSWORD=couchdb
                - COUCHDB_SECRET=mysecret
                - NODENAME={{ansible_default_ipv4.address}}
            image: couchdb:latest