---
- name: Make sure docker is running
  ansible.builtin.systemd:
    state: started
    name: docker

- name: Create a directory to save docker proxy configuration
  become: yes
  ansible.builtin.file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    mode: '0755'

- name: Create a directory to save docker proxy configuration
  become: yes
  ansible.builtin.file:
    path: /etc/systemd/system/docker.service.d/http-proxy.conf
    state: touch
    mode: '0755'

- name: Add proxy in http-proxy.conf
  become: yes
  blockinfile:
    path: /etc/systemd/system/docker.service.d/http-proxy.conf
    block: |
      [Service]
      Environment="HTTP_PROXY=http://wwwproxy.unimelb.edu.au:8000"
      Environment="HTTPS_PROXY=http://wwwproxy.unimelb.edu.au:8000"
      Environment="http_proxy=http://wwwproxy.unimelb.edu.au:8000"
      Environment="https_proxy=http://wwwproxy.unimelb.edu.au:8000"
      Environment="no_proxy=localhost,127.0.0.1,localaddress,172.16.0.0/12,.melbourne.rc.nectar.org.au,.storage.unimelb.edu.au,.cloud.unimelb.edu.au"

- name: Issue deamon_reloaded and restart docker to pick up config change
  become: yes
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    name: docker

- name: Add the user 'ubuntu' to group 'docker'
  become: yes
  ansible.builtin.user:
    name: '{{ remote_username }}'
    group: docker
    append: yes

- name: reset ssh connection to allow user changes to affect ansible user
  ansible.builtin.meta:
    reset_connection