---
- name: Deploy backend services
  community.docker.docker_compose:
    project_name: backend
    definition:
      version: '3.7'
      services:
        backend:
          image: cyrilcsr/ccc_backend:1.5
          container_name: backend
          volumes:
            - /home/ubuntu/config:/home/config
          ports:
            - "5000:5000"
          restart: always