- name: Deploy Twitter harvester for vaccine keyword
  ansible.builtin.shell: >
    docker service create 
    --name vaccine_harvester
    --constraint node.hostname==database1
    cyrilcsr/ccc_harvester_vaccine:1.0
