---
- name: Deploy Twitter harvester for vaccine keyword
  community.docker.docker_compose:
    project_name: vaccine_harvester
    definition:
      version: '3.7'
      services:
        brand_harvester:
          image: cyrilcsr/ccc_harvester_vaccine:1.0
          container_name: vaccine_harvester
          restart: always