- hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
  vars_files:
    - host_vars/mrc.yaml
  gather_facts: true

  roles:
    - role: openstack-common
    - role: openstack-images
    - role: openstack-volume
    - role: openstack-security-group
    - role: openstack-instance
    # - role: openstack-volume-snapshot
    # - role: openstack-setup
    # - role: add-instance-key

- hosts: instances
  remote_user: '{{ remote_username }}'
  vars_files:
    - host_vars/mrc.yaml
  gather_facts: true

  roles:
    - role: instance-setup