- hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
  vars_files:
    - host_vars/mrc.yaml
  gather_facts: true

  roles:
    - role: openstack-common
    - role: openstack-images
    - role: openstack-volume
    - role: openstack-security-group
    - role: openstack-instance
    # - role: openstack-volume-snapshot

- hosts: instances
  remote_user: '{{ remote_username }}'
  vars_files:
    - host_vars/mrc.yaml
  gather_facts: true

  roles:
    - role: instance-setup
    - role: docker-setup

- hosts: backend
  remote_user: '{{ remote_username }}'
  vars_files:
    - host_vars/mrc.yaml
  gather_facts: true

  roles:
    - role: init-docker-swarm-manager

- hosts: worker
  remote_user: '{{ remote_username }}'
  vars_files:
    - host_vars/mrc.yaml
  gather_facts: true

  roles:
    - role: init-docker-swarm-worker

# Deploy Docker service using docker swarm
# - hosts: backend
#   remote_user: '{{ remote_username }}'
#   vars_files:
#     - host_vars/mrc.yaml
#   gather_facts: true

#   roles:
#     - role: deploy-couchdb2-swarm
#     - role: deploy-couchdb3-swarm
#     - role: deploy-couchdb1-swarm
#     - role: deploy-backend-swarm
#     - role: deploy-frontend-swarm
#     - role: delpoy-vaccine-harvester-swarm
#     - role: deploy-brand-harvester-swarm

    



# Deploy Docker service using docker compose
- hosts: database
  remote_user: '{{ remote_username }}'
  vars_files:
    - host_vars/mrc.yaml
  gather_facts: true

  roles:
    - role: deploy-couchdb

- hosts: backend
  remote_user: '{{ remote_username }}'
  vars_files:
    - host_vars/mrc.yaml
  gather_facts: true

  roles:
    - role: deploy-backend

- hosts: webserver
  remote_user: '{{ remote_username }}'
  vars_files:
    - host_vars/mrc.yaml
  gather_facts: true

  roles:
    - role: deploy-frontend

- hosts: database1
  remote_user: '{{ remote_username }}'
  vars_files:
    - host_vars/mrc.yaml
  gather_facts: true

  roles:
    - role: delpoy-vaccine-harvester

- hosts: database2
  remote_user: '{{ remote_username }}'
  vars_files:
    - host_vars/mrc.yaml
  gather_facts: true

  roles:
    - role: deploy-brand-harvester